# Generated by Django 5.0.3 on 2024-03-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
    ]
