version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile.prod
    ports:
      - "8000:8000"
    container_name: api
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=api.project.settings
      - DEBUG_MODE=false
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:latest
    ports:
        - "5432:5432"
    container_name: postgres
    environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - backend

networks:
  backend:
    driver: bridge
